const solarSystemData = {
    sun: {
        id: "sun",
        cssClass: "sun",
        id_name: "Matahari",
        en_name: "Sun",
        id_type: "Bintang Pusat",
        en_type: "Central Star",
        id_desc: "Matahari adalah bintang katai kuning di pusat Tata Surya kita. Ia merupakan bola raksasa gas panas yang terus menerus mengalami reaksi fusi nuklir dari hidrogen menjadi helium. Gravitasinya yang masif menyatukan seluruh tata surya mulai dari planet dominan hingga komet terkecil. Matahari menghasilkan hampir semua cahaya dan panas yang menopang kehidupan di Bumi.",
        en_desc: "The Sun is a yellow dwarf star at the center of our Solar System. It is a giant ball of hot gas continually undergoing nuclear fusion from hydrogen to helium. Its massive gravity holds the entire solar system together, from the dominant planets to the smallest comets. The Sun produces almost all the light and heat that sustains life on Earth.",
        id_distance: "0 km (Pusat)",
        en_distance: "0 km (Center)",
        id_radius: "696,340 km",
        en_radius: "696,340 km",
        id_mass: "1.989 × 10^30 kg",
        en_mass: "1.989 × 10^30 kg",
        id_gravity: "274 m/s²",
        en_gravity: "274 m/s²",
        id_moons: "0 (Memiliki 8 Planet)",
        en_moons: "0 (Has 8 Planets)",
        id_fact: "Matahari menyumbang 99,86% dari total massa di seluruh Tata Surya!",
        en_fact: "The Sun accounts for 99.86% of the total mass in the entire Solar System!"
    },
    planets: [
        {
            id: "mercury",
            cssClass: "p-mercury",
            id_name: "Merkurius",
            en_name: "Mercury",
            id_type: "Planet Dalam (Terestrial)",
            en_type: "Inner Planet (Terrestrial)",
            id_desc: "Merkurius adalah planet terkecil di Tata Surya dan yang terdekat dengan Matahari. Karena tidak memiliki atmosfer yang signifikan untuk menahan panas, planet ini mengalami fluktuasi suhu paling ekstrem, dari sangat panas di siang hari hingga membekukan di malam hari. Permukaannya sangat mirip dengan Bulan milik Bumi, dipenuhi oleh kawah akibat tumbukan meteor dan komet.",
            en_desc: "Mercury is the smallest planet in the Solar System and the closest to the Sun. Because it lacks a significant atmosphere to retain heat, it experiences the most extreme temperature fluctuations, from extremely hot during the day to freezing at night. Its surface is very similar to Earth's Moon, heavily cratered by meteor and comet impacts.",
            id_distance: "57.9 juta km",
            en_distance: "57.9 million km",
            id_radius: "2,439.7 km",
            en_radius: "2,439.7 km",
            id_mass: "3.301 × 10^23 kg",
            en_mass: "3.301 × 10^23 kg",
            id_gravity: "3.7 m/s²",
            en_gravity: "3.7 m/s²",
            id_moons: "0",
            en_moons: "0",
            id_fact: "Satu tahun di Merkurius (satu kali revolusi keliling Matahari) hanya memakan waktu 88 hari Bumi!",
            en_fact: "A year on Mercury (one revolution around the Sun) takes only 88 Earth days!"
        },
        {
            id: "venus",
            cssClass: "p-venus",
            id_name: "Venus",
            en_name: "Venus",
            id_type: "Planet Dalam (Terestrial)",
            en_type: "Inner Planet (Terrestrial)",
            id_desc: "Meskipun berada di urutan kedua dari Matahari, Venus adalah planet terpanas di Tata Surya. Hal ini disebabkan oleh atmosfer tebal beracun karbon dioksida dan awan asam sulfat kekuningan yang menangkap panas menjadi efek rumah kaca yang tak terkendali. Venus memiliki struktur dan ukuran yang sangat mirip dengan Bumi.",
            en_desc: "Despite being second from the Sun, Venus is the hottest planet in the Solar System. This is due to its thick, toxic atmosphere of carbon dioxide and yellowish sulfuric acid clouds that trap heat into a runaway greenhouse effect. Venus has a structure and size very similar to Earth.",
            id_distance: "108.2 juta km",
            en_distance: "108.2 million km",
            id_radius: "6,051.8 km",
            en_radius: "6,051.8 km",
            id_mass: "4.867 × 10^24 kg",
            en_mass: "4.867 × 10^24 kg",
            id_gravity: "8.87 m/s²",
            en_gravity: "8.87 m/s²",
            id_moons: "0",
            en_moons: "0",
            id_fact: "Matahari terbit dari barat dan tenggelam di timur pada planet Venus karena ia berputar mundur (retrograde).",
            en_fact: "The sun rises in the west and sets in the east on Venus because it spins backward (retrograde rotation)."
        },
        {
            id: "earth",
            cssClass: "p-earth",
            id_name: "Bumi",
            en_name: "Earth",
            id_type: "Planet Dalam (Terestrial)",
            en_type: "Inner Planet (Terrestrial)",
            id_desc: "Bumi, planet unik tempat tinggal kita, adalah satu-satunya tempat di alam semesta yang sejauh ini diketahui menopang kehidupan. Sekitar 71% permukaan Bumi ditutupi oleh air cair yang menopang kehidupan, sementara atmosfernya yang kaya nitrogen dan oksigen melindungi kita dari radiasi matahari yang mematikan dan meteoroid.",
            en_desc: "Earth, our unique home planet, is the only place in the universe presently known to harbor life. About 71% of Earth's surface is covered with life-sustaining liquid water, while its nitrogen and oxygen-rich atmosphere protects us from deadly solar radiation and meteoroids.",
            id_distance: "149.6 juta km",
            en_distance: "149.6 million km",
            id_radius: "6,371 km",
            en_radius: "6,371 km",
            id_mass: "5.972 × 10^24 kg",
            en_mass: "5.972 × 10^24 kg",
            id_gravity: "9.807 m/s²",
            en_gravity: "9.807 m/s²",
            id_moons: "1 (Bulan)",
            en_moons: "1 (The Moon)",
            id_fact: "Sebagian wilayah Bumi tidak memiliki gravitasi yang merata (disebut anomali gravitasi) karena variasi massa kerak bumi.",
            en_fact: "Some areas of Earth have uneven gravity (called gravity anomalies) due to variations in the Earth's crust mass."
        },
        {
            id: "mars",
            cssClass: "p-mars",
            id_name: "Mars",
            en_name: "Mars",
            id_type: "Planet Dalam (Terestrial)",
            en_type: "Inner Planet (Terrestrial)",
            id_desc: "Mars serng disebut sebagai Planet Merah karena hamparan luas iron-okside (karat) pada permukaannya yang memberinya rona kemerahan khas. Mars merupakan planet gurun yang dingin yang menyimpan lembah raksasa, kawah, dan gunung berapi paling masif di Tata Surya kita.",
            en_desc: "Mars is often called the Red Planet because of the vast expanses of iron oxide (rust) on its surface giving it a distinctive reddish hue. Mars is a cold desert planet that features giant canyons, craters, and the most massive volcano in our Solar System.",
            id_distance: "227.9 juta km",
            en_distance: "227.9 million km",
            id_radius: "3,389.5 km",
            en_radius: "3,389.5 km",
            id_mass: "6.39 × 10^23 kg",
            en_mass: "6.39 × 10^23 kg",
            id_gravity: "3.721 m/s²",
            en_gravity: "3.721 m/s²",
            id_moons: "2 (Phobos & Deimos)",
            en_moons: "2 (Phobos & Deimos)",
            id_fact: "Gunung Olympus Mons di Mars memiliki tinggi yang memukau, yakni tiga kali lipat tingginya dari Gunung Everest!",
            en_fact: "Olympus Mons on Mars has an astonishing height, namely three times taller than Mount Everest!"
        },
        {
            id: "jupiter",
            cssClass: "p-jupiter",
            id_name: "Jupiter",
            en_name: "Jupiter",
            id_type: "Planet Luar (Raksasa Gas)",
            en_type: "Outer Planet (Gas Giant)",
            id_desc: "Jupiter adalah raksasa gas yang ukurannya melampaui semua planet digabungkan. Ia didominasi oleh gas hidrogen dan helium yang berputar membentuk pita-pita awan badai ekstrem yang ikonik. Salah satu fitur paling terkenal adalah 'Bintik Merah Raksasa', yakni sebuah badai antisiklon raksasa yang telah berkecamuk setidaknya selama berabad-abad lamanya.",
            en_desc: "Jupiter is a gas giant whose size surpasses all other planets combined. It is dominated by spinning hydrogen and helium gas that forms iconic extreme storm cloud bands. One of its most famous features is the 'Great Red Spot', a giant anticyclonic storm that has been raging for at least centuries.",
            id_distance: "778.5 juta km",
            en_distance: "778.5 million km",
            id_radius: "69,911 km",
            en_radius: "69,911 km",
            id_mass: "1.898 × 10^27 kg",
            en_mass: "1.898 × 10^27 kg",
            id_gravity: "24.79 m/s²",
            en_gravity: "24.79 m/s²",
            id_moons: "95 (Dikonfirmasi per 2024)",
            en_moons: "95 (Confirmed as of 2024)",
            id_fact: "Saking besarnya, Anda bisa memasukkan lebih dari 1.300 planet seukuran Bumi ke dalam Jupiter!",
            en_fact: "It's so massive that you could fit over 1,300 Earth-sized planets inside Jupiter!"
        },
        {
            id: "saturn",
            cssClass: "p-saturn",
            id_name: "Saturnus",
            en_name: "Saturn",
            id_type: "Planet Luar (Raksasa Gas)",
            en_type: "Outer Planet (Gas Giant)",
            id_desc: "Saturnus adalah planet keenam dari Matahari dan permata kosmik sejati dari keluarga Tata Surya dengan sistem cincin yang luar biasa menakjubkan. Tidak seperti yang terlihat, benda megah ini hampir seluruhnya terbentuk dari zat hidrogen dan helium super dingin, dengan cincin transparan yang terbentuk dari puluhan ribu bongkahan es dan debu angkasa.",
            en_desc: "Saturn is the sixth planet from the Sun and the true cosmic jewel of the Solar System family with an astoundingly stunning ring system. Despite its appearance, this majestic sphere is almost entirely made up of super-cooled hydrogen and helium, with transparent rings formed by tens of thousands of chunks of ice and space dust.",
            id_distance: "1.43 miliar km",
            en_distance: "1.43 billion km",
            id_radius: "58,232 km",
            en_radius: "58,232 km",
            id_mass: "5.683 × 10^26 kg",
            en_mass: "5.683 × 10^26 kg",
            id_gravity: "10.44 m/s²",
            en_gravity: "10.44 m/s²",
            id_moons: "146 (Dikonfirmasi tertinggi)",
            en_moons: "146 (Highest confirmed)",
            id_fact: "Massa jenis (kepadatan) planet Saturnus lebih rendah dari air, jadi ia secara hipotetis bisa mengapung di lautan besar!",
            en_fact: "Saturn's density is lower than that of water, so it could hypothetically float in a massive ocean!"
        },
        {
            id: "uranus",
            cssClass: "p-uranus",
            id_name: "Uranus",
            en_name: "Uranus",
            id_type: "Planet Luar (Raksasa Es)",
            en_type: "Outer Planet (Ice Giant)",
            id_desc: "Uranus dikenal unik karena kemiringan rotasinya nyaris melintang yang menyebabkan ia terlihat berputar menyamping (menggelinding). Ia tergolong sebagai Raksasa Es bersama Neptunus karena, tidak seperti Jupiter dan Saturnus, mantel utamanya terdiri dari campuran cairan superkritikal es, air, amonia, serta metana super padat.",
            en_desc: "Uranus is uniquely known for its nearly transverse rotational tilt, causing it to appear to rotate sideways (rolling). It is classified as an Ice Giant along with Neptune because, unlike Jupiter and Saturn, its primary mantle consists of a supercritical fluid mixture of densely packed ice, water, ammonia, and methane.",
            id_distance: "2.87 miliar km",
            en_distance: "2.87 billion km",
            id_radius: "25,362 km",
            en_radius: "25,362 km",
            id_mass: "8.681 × 10^25 kg",
            en_mass: "8.681 × 10^25 kg",
            id_gravity: "8.69 m/s²",
            en_gravity: "8.69 m/s²",
            id_moons: "28",
            en_moons: "28",
            id_fact: "Uranus memegang rekor sebagai planet terdingin di Tata Surya, dengan suhu amblas ke angka merinding -224°C.",
            en_fact: "Uranus holds the record for the coldest planet in the Solar System, with temperatures plummeting to a chilling -224°C."
        },
        {
            id: "neptune",
            cssClass: "p-neptune",
            id_name: "Neptunus",
            en_name: "Neptune",
            id_type: "Planet Luar (Raksasa Es)",
            en_type: "Outer Planet (Ice Giant)",
            id_desc: "Planet yang kesepian dan sangat redup ini berada jauh di kegelapan Tata Surya, menjadi satu-satunya yang tidak kasat mata oleh pandangan mata telanjang dari manusia di Bumi. Neptunus dipenuhi lautan es kental bercampur lautan amonia, terkenal melepaskan angin berkecepatan paling menakutkan yang pernah di ukur dalam sejarah Tata Surya.",
            en_desc: "This lonely and very dim planet lies deep in the darkness of the Solar System, being the only one invisible to the naked eye of humans on Earth. Neptune is filled with dark oceans of thick ice mixed with ammonia, famously unleashing the most terrifyingly high-speed winds ever measured in the Solar System's history.",
            id_distance: "4.5 miliar km",
            en_distance: "4.5 billion km",
            id_radius: "24,622 km",
            en_radius: "24,622 km",
            id_mass: "1.024 × 10^26 kg",
            en_mass: "1.024 × 10^26 kg",
            id_gravity: "11.15 m/s²",
            en_gravity: "11.15 m/s²",
            id_moons: "16",
            en_moons: "16",
            id_fact: "Badai angin mematikan di Neptunus bisa berhembus melesat hingga sangat mustahil 2.100 kilometer per jam!",
            en_fact: "Lethal wind storms on Neptune can blow up to an impossible 2,100 kilometers per hour!"
        }
    ],
    translations: {
        id: {
            splashTitle: "MEMASUKI TATA SURYA...",
            headerSubtitle: "Eksplorasi Tata Surya",
            sunLabel: "Matahari",
            typeLabel: "Kategori",
            distanceLabel: "Jarak dari Matahari",
            radiusLabel: "Radius",
            massLabel: "Massa",
            gravityLabel: "Gravitasi",
            moonsLabel: "Satelit Alami",
            factLabel: "Fakta Menarik:"
        },
        en: {
            splashTitle: "ENTERING SOLAR SYSTEM...",
            headerSubtitle: "Solar Exploration",
            sunLabel: "Sun",
            typeLabel: "Category",
            distanceLabel: "Distance from Sun",
            radiusLabel: "Radius",
            massLabel: "Mass",
            gravityLabel: "Gravity",
            moonsLabel: "Moons",
            factLabel: "Fun Fact:"
        }
    }
};
